-- Migration 004: Add checklist fields to trades table
ALTER TABLE trades ADD COLUMN IF NOT EXISTS plan_match BOOLEAN DEFAULT FALSE;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS risk_ok BOOLEAN DEFAULT FALSE;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS rr_ok BOOLEAN DEFAULT FALSE;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS confirmation BOOLEAN DEFAULT FALSE;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS screenshot_ready BOOLEAN DEFAULT FALSE;
